#!/usr/bin/php -q
<?php

require_once dirname(dirname(__FILE__)).'/src/GAP_Authenticator.php';

$gap = new GAP_Authenticator();
$key = $gap->generateSecret(TRUE);

echo "\n";
echo '* Random secret key: '."\n";
echo '    '.$key."\n";

