#!/usr/bin/php -q
<?php

if ($argc != 2) {
	die("Usage:\n\t$argv[0] <secret_key>\n\n");
}
$key = $argv[1];

require_once dirname(dirname(__FILE__)).'/src/GAP_Authenticator.php';

try {
	$gap = new GAP_Authenticator();
	$code = $gap->getTOTPCode($key);

	echo "\n";
	echo '* TOTP code: '."\n";
	echo '    '.$code."\n";

} catch (GAP_InvalidSecretKey $e) {
	echo "\n";
	echo '* ERROR: '.$e->getMessage()."\n\n";
}


